import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    en: {
        home: "Home",
        claim: "Claim",
        register: "Register Now",
        play: "Play Now",
        unlock: "Unlock",
        locked: "Locked",
        enterCode: "Enter Code",
        verify: "Verify",
        askAdmin: "Message Admin",
        winners: "Winners Circle",
        rewards: "Unlock Rewards",
        account: "Account Number",
        workplace: "Workplace",
        welcome: "Win Big Today!",
        messageAdmin: "Message Admin",
        wrongCode: "Wrong Code",
        wrongCodeMessage: "The code you entered is incorrect. Please chat with admin to get the correct code and try again.",
        chatAdmin: "Chat Admin",
        tryAgain: "Try Again",
        congratulations: "Congratulations!",
        wonMessage: "You've won",
        claimPrize: "Chat with admin to claim your prize",
        welcomeBack: "Welcome Back!",
        alreadyQualified: "You have already qualified for the rewards.",
        goToClaimPage: "Go to Claim Page",
        close: "Close",
        verifying: "Verifying...",
        getCodeFromAdmin: "Get Code from Admin",
        pleaseEnterCode: "Please enter a code",
        invalidCode: "Invalid code. Please try again or chat admin for the correct code.",
        networkError: "Network error. Please try again or chat admin.",
        winInstantly: "Win instantly!",
        // Prizes Page
        prizesGallery: "Prizes Gallery",
        explorePrizes: "Explore the suggested prizes you can win. Actual prizes and amounts may vary per campaign.",
        cash10k: "$10,000 Cash",
        cash50k: "$50,000 Cash",
        cash100k: "$100,000 Cash",
        cash500k: "$500,000 Cash",
        cash1000000: "$1,000,000 Cash",
        bankTransfer: "Bank transfer",
        luxuryCar: "Luxury Car",
        sportsCar: "Sports Car",
        modernHouse: "Modern House",
        shoppingVoucher: "Shopping Voucher",
        latestModel: "Latest model",
        beautifulHome: "Beautiful home",
        voucherHundredK: "$100,000 Voucher",
        vacationPackage: "Vacation Package",
        fiveNights: "14 nights",
        giftCard: "Gift Card",
        shopVoucher: "Shop voucher",
        // Car Models
        mercedesBenz: "Mercedes-Benz S-Class",
        bmwX7: "BMW X7",
        teslaModelS: "Tesla Model S",
        rangeRoverSport: "Range Rover Sport",
        audiA8: "Audi A8",
        porsche911: "Porsche 911",
        // House Types
        luxuryVilla: "Luxury Villa",
        modernApartment: "Modern Apartment",
        beachHouse: "Beach House",
        penthouse: "Penthouse",
        countryside: "Countryside Manor",
        // Vouchers
        fashionVoucher: "Fashion Voucher",
        electronicsVoucher: "Electronics Voucher",
        travelVoucher: "Travel Voucher",
        diningVoucher: "Dining Voucher",
        homeDecorVoucher: "Home Decor Voucher",
        backHome: "Back Home",
        // Quiz Page
        question: "Question",
        of: "of",
        marks: "Marks",
        hardLuck: "Hard Luck!",
        youScored: "You scored",
        youNeedAtLeast: "You need at least 20 to qualify.",
        claimYourPrize: "Claim Your Prize",
        capitalOfSaudiArabia: "What is the capital of Saudi Arabia?",
        redPlanet: "Which planet is known as the Red Planet?",
        rainbowColors: "How many colors are there in a rainbow?",
        multiplyFiveByFive: "What is 5 multiplied by 5?",
        fastestLandAnimal: "Which is the fastest land animal?",
        dubai: "Dubai",
        riyadh: "Riyadh",
        jeddah: "Jeddah",
        mecca: "Mecca",
        venus: "Venus",
        mars: "Mars",
        jupiter: "Jupiter",
        saturn: "Saturn",
        five: "5",
        six: "6",
        seven: "7",
        eight: "8",
        twenty: "20",
        twentyfive: "25",
        thirty: "30",
        ten: "10",
        lion: "Lion",
        cheetah: "Cheetah",
        horse: "Horse",
        tiger: "Tiger",
        // Help Page
        helpCenter: "Help Center",
        needAssistance: "Need assistance? Here are some quick steps:",
        helpStep1: "Make sure you are registered through the Register page.",
        helpStep2: "If you have issues with rewards, message the admin via the Telegram link provided in the app.",
        helpStep3: "For payment or prize fulfillment, we will request verification details.",
        // Terms Page
        termsConditions: "Terms & Conditions",
        termsText1: "This demo app is for illustrative purposes. By participating you agree to the following:",
        termsItem1: "Prizes are distributed at the discretion of the organizer.",
        termsItem2: "Winners may be required to provide identity verification to claim prizes.",
        termsItem3: "Personal data will be used solely for prize fulfillment.",
        termsText2: "Replace these placeholders with your real terms before launching.",
        // Winners Page
        winnersCircle: "Winners Circle",
        winnersCongrats: "Congratulations to recent winners! This page contains anonymized, verified winner listings and prize details.",
        winner: "Winner",
        prize: "Prize",
        sanaK: "Sana K.",
        omarA: "Omar A.",
        linaH: "Lina H.",
        thousandDollar: "$1,000",
        vacation: "Vacation",
        // Register Page
        signUp: "Sign Up",
        signingUpAs: "Signing up as",
        telegramID: "Telegram ID:",
        createAccount: "Creating Account...",
        continueToQuiz: "Continue to Quiz",
        firstName: "First Name",
        lastName: "Last Name",
        phone: "Phone Number",
        email: "Email Address",
        age: "Age",
        country: "Country",
        workplace: "Workplace",
        firstNamePlaceholder: "John",
        lastNamePlaceholder: "Doe",
        phonePlaceholder: "+2348012345678",
        emailPlaceholder: "john@example.com",
        agePlaceholder: "Age",
        countryPlaceholder: "Your Country",
        workplacePlaceholder: "Your Workplace",
        // Claim Profile Page
        name: "Full Name",
        country: "Country",
        claimPageTitle: "Your Prize Claim Profile",
        userInformation: "User Information",
        claimInstruction: "Please verify your details. Prizes will be sent based on this information.",
        registerToClaim: "Register to Claim",
        takeQuizToClaim: "Take Quiz to Claim",
        messageAdminToClaim: "Message Admin to Claim",
        registerToClaimModal: "Register to Claim",
        registerToClaimDesc: "You need to register to be eligible for rewards. Tap below to complete your registration.",
        registerNow: "Register Now",
        cancel: "Cancel",
        email: "Email Address",
        accountNumber: "Account Number",
        loadingProfile: "Loading Profile...",
        notProvided: "Not provided",
        // Menu and Navigation
        menu: "Menu",
        homeMenu: "Home",
        winnersMenu: "Winners",
        prizesMenu: "Prizes",
        termsMenu: "Terms and Conditions",
        helpMenu: "Help",
        changeLanguage: "Change Language",
        english: "English",
        arabic: "العربية",
        copyright: "© 2022. Dream All Right Reserved."
    },
    ar: {
        home: "الرئيسية",
        claim: "المكافآت",
        register: "سجل الآن",
        play: "العب الآن",
        unlock: "فتح القفل",
        locked: "مقفول",
        enterCode: "أدخل الكود",
        verify: "تحقق",
        askAdmin: "راسل المسؤول",
        winners: "قائمة الفائزين",
        rewards: "فتح المكافآت",
        account: "رقم الحساب",
        workplace: "مكان العمل",
        welcome: "اربح الكثير اليوم!",
        messageAdmin: "راسل المسؤول",
        wrongCode: "كود خاطئ",
        wrongCodeMessage: "الكود الذي أدخلته غير صحيح. يرجى التحدث مع المسؤول للحصول على الكود الصحيح والمحاولة مرة أخرى.",
        chatAdmin: "راسل المسؤول",
        tryAgain: "حاول مرة أخرى",
        congratulations: "مبروك!",
        wonMessage: "لقد فزت بـ",
        claimPrize: "تحدث مع المسؤول للمطالبة بجائزتك",
        welcomeBack: "أهلا وسهلا!",
        alreadyQualified: "لقد تأهلت بالفعل للحصول على الجوائز.",
        goToClaimPage: "انتقل إلى صفحة المطالبة",
        close: "إغلاق",
        verifying: "جارٍ التحقق...",
        getCodeFromAdmin: "احصل على الكود من المسؤول",
        pleaseEnterCode: "يرجى إدخال كود",
        invalidCode: "كود غير صحيح. يرجى المحاولة مرة أخرى أو التحدث مع المسؤول.",
        networkError: "خطأ في الشبكة. يرجى المحاولة مرة أخرى أو التحدث مع المسؤول.",
        winInstantly: "اربح على الفور!",
        // Prizes Page
        prizesGallery: "معرض الجوائز",
        explorePrizes: "استكشف الجوائز المقترحة التي يمكنك الفوز بها. قد تختلف الجوائز والمبالغ الفعلية حسب الحملة.",
        cash10k: "10,000 دولار نقدا",
        cash50k: "50,000 دولار نقدا",
        cash100k: "100,000 دولار نقدا",
        cash500k: "500,000 دولار نقدا",
        cash1000000: "1,000,000 دولار نقدا",
        bankTransfer: "تحويل بنكي",
        luxuryCar: "سيارة فاخرة",
        sportsCar: "سيارة رياضية",
        modernHouse: "منزل حديث",
        shoppingVoucher: "قسيمة تسوق",
        latestModel: "آخر موديل",
        beautifulHome: "منزل جميل",
        voucherHundredK: "100,000 دولار قسيمة",
        vacationPackage: "عطلة سفر",
        fiveNights: "14 ليلة",
        giftCard: "بطاقة هدية",
        shopVoucher: "قسيمة تسوق",
        // Car Models
        mercedesBenz: "مرسيدس-بنز S-Class",
        bmwX7: "BMW X7",
        teslaModelS: "تسلا Model S",
        rangeRoverSport: "Range Rover Sport",
        audiA8: "أودي A8",
        porsche911: "بورشه 911",
        // House Types
        luxuryVilla: "فيلا فاخرة",
        modernApartment: "شقة حديثة",
        beachHouse: "منزل على الشاطئ",
        penthouse: "بنتهاوس",
        countryside: "منزل ريفي",
        // Vouchers
        fashionVoucher: "قسيمة ملابس",
        electronicsVoucher: "قسيمة إلكترونيات",
        travelVoucher: "قسيمة سفر",
        diningVoucher: "قسيمة مطاعم",
        homeDecorVoucher: "قسيمة ديكور منزلي",
        backHome: "العودة للرئيسية",
        // Quiz Page
        question: "السؤال",
        of: "من",
        marks: "درجات",
        hardLuck: "للأسف!",
        youScored: "لقد حصلت على",
        youNeedAtLeast: "تحتاج إلى 20 على الأقل للتأهل.",
        claimYourPrize: "اطلب جائزتك",
        capitalOfSaudiArabia: "ما هي عاصمة المملكة العربية السعودية؟",
        redPlanet: "أي كوكب يُعرف بالكوكب الأحمر؟",
        rainbowColors: "كم عدد الألوان في قوس قزح؟",
        multiplyFiveByFive: "كم يساوي 5 مضروب في 5؟",
        fastestLandAnimal: "أي من الحيوانات البرية الأسرع؟",
        dubai: "دبي",
        riyadh: "الرياض",
        jeddah: "جدة",
        mecca: "مكة",
        venus: "الزهرة",
        mars: "المريخ",
        jupiter: "المشتري",
        saturn: "زحل",
        five: "5",
        six: "6",
        seven: "7",
        eight: "8",
        twenty: "20",
        twentyfive: "25",
        thirty: "30",
        ten: "10",
        lion: "الأسد",
        cheetah: "الفهد",
        horse: "الحصان",
        tiger: "النمر",
        // Help Page
        helpCenter: "مركز المساعدة",
        needAssistance: "تحتاج إلى المساعدة؟ إليك بعض الخطوات السريعة:",
        helpStep1: "تأكد من أنك مسجل من خلال صفحة التسجيل.",
        helpStep2: "إذا كان لديك مشاكل في المكافآت، راسل المسؤول عبر رابط التيليجرام المرفق في التطبيق.",
        helpStep3: "للدفع أو الحصول على الجائزة، قد نطلب منك تفاصيل التحقق.",
        // Terms Page
        termsConditions: "الشروط والأحكام",
        termsText1: "هذا التطبيق التوضيحي لأغراض توضيحية فقط. بالمشاركة، فإنك توافق على ما يلي:",
        termsItem1: "يتم توزيع الجوائز وفقاً لتقدير المنظم.",
        termsItem2: "قد يُطلب من الفائزين تقديم تحقق من الهوية للمطالبة بالجوائز.",
        termsItem3: "سيتم استخدام البيانات الشخصية فقط لتنفيذ الجوائز.",
        termsText2: "استبدل هذه العناصر النموذجية بشروطك الفعلية قبل الإطلاق.",
        // Winners Page
        winnersCircle: "قائمة الفائزين",
        winnersCongrats: "تهانينا للفائزين مؤخراً! تحتوي هذه الصفحة على قوائم الفائزين المتحققة والمجهولة والتفاصيل الجائزة.",
        winner: "الفائز",
        prize: "الجائزة",
        sanaK: "سناء ك.",
        omarA: "عمر ع.",
        linaH: "لينا ح.",
        thousandDollar: "1000 دولار",
        vacation: "عطلة",
        // Register Page
        signUp: "التسجيل",
        signingUpAs: "التسجيل باسم",
        telegramID: "معرف التيليجرام:",
        createAccount: "إنشاء حساب...",
        continueToQuiz: "المتابعة إلى الاختبار",
        firstName: "الاسم الأول",
        lastName: "اسم العائلة",
        phone: "رقم الهاتف",
        email: "عنوان البريد الإلكتروني",
        age: "العمر",
        country: "الدولة",
        workplace: "مكان العمل",
        firstNamePlaceholder: "أحمد",
        lastNamePlaceholder: "محمد",
        phonePlaceholder: "+2348012345678",
        emailPlaceholder: "ahmed@example.com",
        agePlaceholder: "العمر",
        countryPlaceholder: "دولتك",
        workplacePlaceholder: "مكان عملك",
        // Claim Profile Page
        name: "الاسم الكامل",
        country: "الدولة",
        claimPageTitle: "ملف مطالبتك بالجائزة",
        userInformation: "معلومات المستخدم",
        claimInstruction: "يرجى التحقق من تفاصيلك. ستُرسل الجوائز بناءً على هذه المعلومات.",
        registerToClaim: "سجل للمطالبة",
        takeQuizToClaim: "أكمل الاختبار للمطالبة",
        messageAdminToClaim: "راسل المسؤول للمطالبة",
        registerToClaimModal: "سجل للمطالبة",
        registerToClaimDesc: "تحتاج إلى التسجيل لتكون مؤهلاً للحصول على المكافآت. اضغط أدناه لإكمال التسجيل الخاص بك.",
        registerNow: "سجل الآن",
        cancel: "إلغاء",
        email: "عنوان البريد الإلكتروني",
        accountNumber: "رقم الحساب",
        loadingProfile: "جاري تحميل الملف الشخصي...",
        notProvided: "لم يتم توفيره",
        // Menu and Navigation
        menu: "القائمة",
        homeMenu: "الرئيسية",
        winnersMenu: "الفائزون",
        prizesMenu: "الجوائز",
        termsMenu: "الشروط والأحكام",
        helpMenu: "مساعدة",
        changeLanguage: "تغيير اللغة",
        english: "English",
        arabic: "العربية",
        copyright: "© 2022. جميع الحقوق محفوظة للحلم."
    }
};

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState('en');

    const toggleLang = () => {
        setLang((prev) => (prev === 'en' ? 'ar' : 'en'));
    };

    useEffect(() => {
        // INSTANTLY FLIP THE HTML DIRECTION
        document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = lang;
    }, [lang]);

    return (
        <LanguageContext.Provider value={{ t: translations[lang], lang, toggleLang }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLang = () => useContext(LanguageContext);